# Generated by Django 5.1.7 on 2025-03-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('sport_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='athlete_profiles/')),
                ('contact_info', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificate_images/')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='mainapp.athlete')),
            ],
        ),
    ]
