# Generated by Django 5.1.7 on 2025-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_athleteprofile_event_job_scholarship_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='sport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
