# Generated by Django 5.1.6 on 2025-03-27 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_athleteprofile_achievements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='athleteprofile',
            name='sport',
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='athleteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
