# Generated by Django 5.1.7 on 2025-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('Sportsperson', 'Sportsperson'), ('Organizer', 'Organizer')], default='Sportsperson', max_length=20),
        ),
    ]
