# Generated by Django 5.1.7 on 2025-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_age_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Athlete', 'Athlete'), ('Trainer', 'Trainer'), ('Organizer', 'Organizer')], default='Athlete', max_length=20),
        ),
    ]
